### ISSUE TITLE
Typo - Breathe/Breath

### ISSUE THREAD

**Issue by Nasawa** [RichieUltimate/ultimate-trial#2]
`ultimate_trial_1.02_n64.bps:95583`:  AHydrothermal Tunic   40 Rupees@ A tunic that grants power! Itprotects you from heat damage andlets you ~~breath~~ __breathe__ under water.	

Watched the ZFG playthrough. Great work! :D

**Comment by RichieUltimate** [comment]
Thanks! It's fixed for the next version :)
