### ISSUE TITLE
Crash during Phantom Gannon fight.

### ISSUE THREAD

**Issue by pixel-stuck** [RichieUltimate/ultimate-trial#3]
Emulator: Simple64 build f5e21b0

During the Phantom Gannon fight I encountered a crash when getting hit with a green ball I failed to parry.

Crash info:
![image](https://github.com/RichieUltimate/ultimate-trial/assets/3634616/545b2bd5-7690-453a-ad1f-7bbe42d70176)
![image](https://github.com/RichieUltimate/ultimate-trial/assets/3634616/740a59bf-9991-4d50-9ae4-83d71b4fbe2a)
![image](https://github.com/RichieUltimate/ultimate-trial/assets/3634616/5281e822-84fe-4782-8bf2-42ff66024371)
![image](https://github.com/RichieUltimate/ultimate-trial/assets/3634616/63273928-a483-464a-bd04-2ef4dd25430b)
![image](https://github.com/RichieUltimate/ultimate-trial/assets/3634616/3e468b19-0270-4269-9b72-2c038c4e1a3f)
![image](https://github.com/RichieUltimate/ultimate-trial/assets/3634616/04b143e0-d895-4618-b159-0efc66c68ed7)
![image](https://github.com/RichieUltimate/ultimate-trial/assets/3634616/b4e8456a-762f-4d13-bc41-3bf1f9c0e032)

If helpful, I can also provide a savestate

**Comment by RichieUltimate** [comment]
Thank you for reporting it and very sorry for the late answer! We identified the issue and we have fixed it. The fix will be available on 1.04 version

**Comment by pixel-stuck** [comment]
No worries, glad you were able to figure it out. Thanks to you and the team for the fun hack
