### ISSUE TITLE
Typo in character dialogue

### ISSUE THREAD

**Issue by MikeSS8** [RichieUltimate/ultimate-trial#4]
The blobby fella by the entrance misspells "hereditary."  I pulled and grepped to make sure it's still like this in the current version:

>Extra! Extra!A man named BGrant@ was spottedheading over towards the DGarden@.He was carrying around a music boxwhich was a little shocking. Heseems to really love music. Maybeit's a heriditary thing?

**Comment by RichieUltimate** [comment]
Thanks for reporting it! We didn't even notice this typo, and it'll be corrected in the next version!
