### ISSUE TITLE
Fatal Error at Stronghold

### ISSUE THREAD

**Issue by darkmage0707077** [RichieUltimate/ultimate-trial#7]
Downloaded 1.05 and patched it successfully - no errors with the patcher, and the new ROM boots up using Project64 without issue, either. Created a new file, and went through the intro portion fine up until the Stronghold Entrance.

However, every time I try to enter the Stronghold for the first time, I get a message "Fatal Error: Stopping Emulation". It repeats 7 times, then the ROM closes and I'm back to the ROM select screen.

I'm using Project64 v3.0.1.5664. Changing screen resolution, full- or window-mode, selecting Rumble or Memory pack for controller doesn't do anything to fix it. Nor does switching out controllers entirely, from an OG N64 controller with a special USB dongle that allows full Rumble/Memory Cart support to as a basic Logitech game pad. I've not changed any settings from defaults in-game, either.

**Comment by RichieUltimate** [comment]
There is an option you need to enable in the Project64 settings.

You need to enable the "Always use interpreter core" option.

Make sure to uncheck the "hide advanced settings" first to find this option. 

Have fun!

**Comment by darkmage0707077** [comment]
Yep, ironically discovered this on my own today - works fine now.

I recall checking the readme on the repo when I first posted and didn't see anything about it there. Glad you've added it.

We should be good, so thanks for looking into it!
