### ISSUE TITLE
N64 (Real Hardware) - Warp Crash

### ISSUE THREAD

**Issue by neovol** [RichieUltimate/ultimate-trial#8]
Game appears to crash when trying to re-use the warp when playing on N64. This was also reported in the romhacking.net review section by a separate user. I am playing on a real N64 using an Ultra Everdrive 64 V3 on the latest available firmware with an expansion pack.

The crash was captured while streaming:
https://www.twitch.tv/volwrath/clip/CheerfulChillySparrowSpicyBoy-dkVQtUp88-4MwjlF

**Comment by RichieUltimate** [comment]
Hey, thanks for reporting the bug !

Following your post, we did some testing and were able to identify the issue and fixed it. The fix will then be available in the next release. Stay tuned!
